insert into public.services (title, slug, short_description, who_it_is_for, what_is_included, deliverables, status, sort_order) values
('Landing Page Development', 'landing-page-development', 'Focused pages built to explain one offer clearly and convert serious visitors.', 'Founders, consultants, and small teams launching a specific offer or campaign.', '["Content structure", "Responsive design", "Next.js implementation", "Analytics-ready deployment"]', '["Production landing page", "Contact or quote form", "Deployment support"]', 'published', 1),
('Business Website Development', 'business-website-development', 'Professional websites for businesses that need trust, clarity, and room to grow.', 'Businesses that need a strong web presence without a bloated marketing site.', '["Information architecture", "Service pages", "CMS-ready content model", "SEO foundation"]', '["Responsive business website", "Admin-editable content", "Launch checklist"]', 'published', 2),
('Web App / Dashboard Development', 'web-app-dashboard-development', 'Internal tools and dashboards for workflows that outgrow spreadsheets and manual tracking.', 'Teams that need authenticated systems, reporting, admin panels, and workflow screens.', '["Data model planning", "Authenticated screens", "Role-aware admin flows", "Database-backed workflows"]', '["Web app or dashboard", "Database schema", "Deployment documentation"]', 'published', 3),
('Website Redesign', 'website-redesign', 'A structured rebuild for websites that need sharper UX, stronger performance, and cleaner messaging.', 'Businesses with an existing website that no longer matches the quality of their work.', '["UX audit", "Content cleanup", "Visual redesign", "Performance improvements"]', '["Redesigned website", "Migration guidance", "Before/after notes"]', 'published', 4),
('Technical Consultation', 'technical-consultation', 'Practical technical direction for teams deciding what to build, fix, or simplify next.', 'Business owners, founders, and teams that need engineering judgment before committing budget.', '["Architecture review", "Stack guidance", "Deployment review", "Implementation roadmap"]', '["Technical recommendation", "Prioritized action plan", "Follow-up notes"]', 'published', 5)
on conflict (slug) do update set title = excluded.title, short_description = excluded.short_description, who_it_is_for = excluded.who_it_is_for, what_is_included = excluded.what_is_included, deliverables = excluded.deliverables, status = excluded.status, sort_order = excluded.sort_order;

insert into public.projects (title, slug, excerpt, summary, category, year, role, focus, status, featured, stack, cover_image_url, problem, goal, my_role, tech_stack, key_features, architecture_flow, challenges, outcome, what_i_learned, sort_order) values
('Operations Dashboard Blueprint', 'operations-dashboard-blueprint', 'A reference dashboard concept for turning scattered business activity into a clear operating view.', 'A portfolio-ready example showing how Kavin HQ approaches dashboards, metrics, and admin workflows without claiming a client result.', 'Dashboard', '2026', 'Product engineer', 'Workflow visibility', 'published', true, array['Next.js','Supabase','PostgreSQL','Tailwind'], '/images/placeholders/project.svg', 'Small teams often track operational work across chat, spreadsheets, and disconnected tools.', 'Design a single dashboard model that can surface status, ownership, and recent activity.', 'I shaped the product flow, data model, and interface system.', 'Next.js App Router, Supabase PostgreSQL, Tailwind CSS, protected admin routes.', '["Status overview", "Recent activity stream", "Role-aware management screens"]', 'Public site collects inquiries, admin reviews records, dashboard summarizes work queues.', 'The challenge is keeping the interface dense enough for repeated use without making it feel heavy.', 'A clean dashboard pattern ready to adapt to a real business workflow.', 'Dashboards work best when they answer a few operational questions very quickly.', 1),
('Service Website System', 'service-website-system', 'A structured business website pattern for service providers who need clarity and trust.', 'A realistic editable portfolio example for service pages, case studies, notes, and contact workflows.', 'Business Website', '2026', 'Full-stack engineer', 'Conversion clarity', 'published', true, array['Next.js','React','Vercel','Supabase'], '/images/placeholders/project.svg', 'Service businesses need websites that communicate clearly and stay easy to maintain.', 'Create a scalable website structure with services, work, notes, and inquiry capture.', 'I designed the information architecture, content model, and implementation approach.', 'Next.js, Supabase, Tailwind, Server Actions.', '["Service taxonomy", "Lead inquiry form", "Admin-editable content"]', 'Visitors move from service context to work proof to inquiry submission.', 'The main constraint is balancing premium presentation with fast, practical navigation.', 'A maintainable website foundation suitable for real business growth.', 'A premium site still has to make the next action obvious.', 2),
('Technical Notes Hub', 'technical-notes-hub', 'A markdown-backed writing system for engineering notes and implementation decisions.', 'An example content system for publishing technical notes safely from an admin dashboard.', 'Content System', '2026', 'Full-stack engineer', 'Knowledge publishing', 'published', false, array['Markdown','Next.js','PostgreSQL'], '/images/placeholders/note.svg', 'Technical decisions get lost when they are not written down in a useful place.', 'Build a notes system that supports searchable public writing and admin-managed drafts.', 'I created the content model, public rendering, and admin editor.', 'Supabase notes table, markdown rendering with sanitization, App Router pages.', '["Draft and published status", "Tags and categories", "Safe markdown rendering"]', 'Admin writes markdown, public route renders published notes with metadata.', 'Markdown should be flexible without exposing unsafe HTML.', 'A simple publishing workflow that can evolve into a richer editor later.', 'Start with boring reliable editing before adding editorial complexity.', 3)
on conflict (slug) do nothing;

insert into public.notes (title, slug, excerpt, content, category, tags, cover_image_url, status, published_at, read_time, seo_title, seo_description) values
('How I Think About Business Websites', 'how-i-think-about-business-websites', 'A business website should make the offer clear, reduce doubt, and give the visitor a practical next step.', '## Clarity before decoration\n\nA business website is not a gallery. It is a decision surface.\n\n## Systems thinking\n\nThe useful parts are content structure, speed, trust, conversion paths, and maintenance.\n\n## The practical result\n\nA good website helps a serious visitor understand what you do and decide what to do next.', 'Websites', array['websites','ux','business'], '/images/placeholders/note.svg', 'published', now(), 4, 'How I Think About Business Websites', 'A practical note on clear business website systems.'),
('Dashboards Need Fewer Surprises', 'dashboards-need-fewer-surprises', 'Internal tools should be calm, scannable, and designed for repeated work.', '## Repeated use changes the design\n\nDashboards are used under pressure. The interface should be predictable.\n\n## Useful density\n\nA dashboard can be information-rich without feeling crowded when hierarchy is clear.\n\n## Reliability\n\nThe best internal tool is one people trust enough to stop using the spreadsheet beside it.', 'Dashboards', array['dashboards','systems','ux'], '/images/placeholders/note.svg', 'published', now(), 3, 'Dashboards Need Fewer Surprises', 'A note on practical dashboard UX.')
on conflict (slug) do nothing;

insert into public.site_settings (key, value) values
('homepage', '{"headline":"I build clean, reliable digital systems for businesses, teams, and real-world workflows.","subheadline":"Kavin HQ is the home base for my software work, case studies, technical notes, and business-focused web solutions.","availability":"Open for selected projects","contact_email":"kavindra.senanayake@gmail.com","social_links":{}}')
on conflict (key) do update set value = excluded.value;
