insert into public.services (slug, title, description, details, icon, status, sort_order) values
('landing-page-development', 'Landing Page Development', 'Focused pages that communicate clearly and move people to act.', 'For launches, campaigns, service offers, and focused conversion pages. I turn the core offer into a clean page with sharp copy structure, responsive UI, and reliable deployment.', 'PanelTop', 'published', 1),
('business-website-development', 'Business Website Development', 'Professional websites that build trust and explain your business well.', 'For companies that need a practical, polished website with clear navigation, service pages, contact flows, and content that can grow over time.', 'Building2', 'published', 2),
('web-app-dashboard-development', 'Web App / Dashboard Development', 'Internal tools and dashboards shaped around real workflows.', 'For teams replacing spreadsheets, manual handoffs, or scattered tools. I build usable interfaces, clean data flows, and secure admin experiences.', 'LayoutDashboard', 'published', 3),
('website-redesign', 'Website Redesign', 'Modernize an existing website without losing what already works.', 'For sites that feel dated, unclear, or hard to maintain. I improve structure, interface quality, performance, and the path from visitor to inquiry.', 'RefreshCw', 'published', 4),
('technical-consultation', 'Technical Consultation', 'Clear technical direction before you commit time and budget.', 'For founders and teams who need help scoping a build, choosing a stack, reviewing an existing system, or turning a rough idea into a buildable plan.', 'MessagesSquare', 'published', 5)
on conflict (slug) do nothing;

insert into public.projects (slug, title, description, overview, problem, goal, what_built, tech_stack, key_features, result, lessons, image, gallery, year, category, status, featured) values
('real-estate-platform', 'Real Estate Platform', 'Property listings, lead capture, and agent workflow tools.', 'A responsive web platform for a property business that needed a clearer way to publish listings, capture inquiries, and manage follow-ups.', 'Listings and customer conversations were scattered across manual channels.', 'Create a polished public experience and a simple operating layer.', 'Listing flow, property pages, inquiry capture, admin views, and reporting basics.', array['Next.js','Laravel','PostgreSQL','Tailwind CSS'], array['Searchable property listings','Lead capture forms','Admin listing management','Inquiry tracking'], 'The business gained a clearer web presence and a more reliable path from visitor interest to follow-up.', 'Operational tools work best when the public experience and back-office flow are designed together.', '/images/project-real-estate.svg', array['/images/project-real-estate.svg','/images/project-dashboard.svg'], '2026', 'Web Applications', 'published', true),
('task-management-system', 'Task Management System', 'A team workspace for tasks, ownership, and reporting.', 'A web system for a small team that needed better visibility across task progress, deadlines, and responsibilities.', 'Work was moving through chat and spreadsheets.', 'Build a clean dashboard that keeps daily work visible.', 'Task boards, status views, filters, role-based access, and summary reporting.', array['Next.js','ASP.NET Core','SQL Server','Tailwind CSS'], array['Task assignment','Status filters','Team dashboards','Role-based access'], 'The team moved recurring work into one place and reduced manual status checking.', 'A good dashboard should reduce questions, not create a new layer of work.', '/images/project-task.svg', array['/images/project-task.svg','/images/project-dashboard.svg'], '2025', 'Dashboards', 'published', true),
('fleetops-dashboard', 'FleetOps Dashboard', 'Fleet and asset management with real-time reporting views.', 'A dashboard concept for monitoring operational assets, maintenance states, and high-priority exceptions.', 'Operational teams needed a faster way to understand asset status.', 'Make exceptions obvious while keeping views calm and readable.', 'Overview metrics, asset tables, detail views, and status-driven filtering.', array['React','Supabase','PostgreSQL','Tailwind CSS'], array['Asset status overview','Maintenance tracking','Filtered tables','Activity summaries'], 'The dashboard made routine checks faster and gave the team a clearer source of truth.', 'Operational interfaces need hierarchy first; decoration comes much later.', '/images/project-dashboard.svg', array['/images/project-dashboard.svg','/images/project-task.svg'], '2025', 'Dashboards', 'published', true)
on conflict (slug) do nothing;

insert into public.notes (slug, title, excerpt, content, date, read_time, category, image, status) values
('building-scalable-web-applications', 'Building Scalable Web Applications', 'A practical look at the decisions that keep a web system maintainable as it grows.', 'Scalable web applications are not created by adding complexity early. They come from clear boundaries, thoughtful data models, predictable interfaces, and a habit of making tradeoffs explicit.', '2026-05-12', '6 min read', 'Engineering', '/images/note-workspace.svg', 'published'),
('designing-dashboards-that-teams-use', 'Designing Dashboards That Teams Use', 'Useful dashboards are quiet, focused, and built around decisions.', 'A dashboard should help someone decide what to do next. That means fewer decorative metrics, stronger grouping, and a clear distinction between overview, exceptions, and detail.', '2026-04-28', '5 min read', 'Design', '/images/note-code.svg', 'published'),
('planning-before-writing-code', 'How I Plan a Project Before Writing Code', 'The questions I use to turn a rough idea into a buildable scope.', 'Planning is not about creating a perfect document. It is about reducing avoidable uncertainty. I start with the outcome, the users, the workflow, the content, and the data that needs to move through the system.', '2026-04-15', '4 min read', 'Process', '/images/note-planning.svg', 'published')
on conflict (slug) do nothing;

insert into public.site_settings (key, value)
values ('brand', '{"name":"Kavin HQ","email":"hello@kavinhq.com"}'::jsonb)
on conflict (key) do nothing;
